version: "3.9"
services:
  postgres:
    container_name: "postgres"
    image: "postgres"
    platform: linux/x86_64
    restart: "always"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ezb_db:/var/lib/postgresql/data
    networks:
      - ezb_network

  server:
    container_name: "strapi"
    build:
      context: .
      dockerfile: Dockerfile
    restart: "always"
    ports:
      - "1337:1337"
    networks:
      - ezb_network
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}

      APP_ADMIN_JWT_SECRET: ${APP_ADMIN_JWT_SECRET}
      APP_API_TOKEN_SALT: ${APP_API_TOKEN_SALT}
      APP_KEYS: ${APP_KEYS}

      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_ACCESS_SECRET: ${AWS_ACCESS_KEY_ID}
      AWS_BUCKET: ${AWS_BUCKET}
      AWS_REGION: ${AWS_REGION}
    depends_on:
      - postgres
volumes:
  ezb_db:
networks:
  ezb_network:
    driver: bridge
